
title: Zahra Lakdawala's homepage
email: zahralakda@gmail.com
description: >- # this means to ignore newlines until "baseurl:"

github_username: zahralakdawala

theme: minima
plugins:
  - jekyll-feed
  - jekyll-toc
